#ifndef UI_METRICS_H
#define UI_METRICS_H

// Backing area
#define XT_UI_PLANE 0
#define XT_UI_AREA_X 0
#define XT_UI_AREA_Y 0
#define XT_UI_AREA_W 512
#define XT_UI_AREA_H 64

// Channel labels
#define XT_UI_CHANLABEL_W 64
#define XT_UI_CHANLABEL_H 8
#define XT_UI_CHANLABEL_Y (XT_UI_AREA_Y + XT_UI_AREA_H - XT_UI_CHANLABEL_H)

// Margins
#define XT_UI_MARGIN_SIDE 8
#define XT_UI_MARGIN_TOP 4

// Section title bars
#define XT_UI_TITLEBAR_TEXT_OFFS_X 2
#define XT_UI_TITLEBAR_TEXT_OFFS_Y 0
#define XT_UI_TITLEBAR_LINE_H 8
#define XT_UI_TITLEBAR_CONTENT_OFFS_Y 12

// Left side elements.
#define XT_UI_LOGO_X 8
#define XT_UI_LOGO_Y 4

#define XT_UI_FOCUS_LABEL_X XT_UI_LOGO_X
#define XT_UI_FOCUS_LABEL_W 128
#define XT_UI_FOCUS_LABEL_Y XT_UI_LOGO_Y + 20
#define XT_UI_FOCUS_LABEL_H 8

// Middle.
#define XT_UI_INSTRUMENT_LIST_X (XT_UI_MARGIN_SIDE + 136)
#define XT_UI_INSTRUMENT_LIST_Y XT_UI_MARGIN_TOP

// Right.

// Arrangement Table.
#define XT_UI_ARRANGEMENT_X (XT_UI_MARGIN_SIDE + 240)
#define XT_UI_ARRANGEMENT_TABLE_OFFS_X 24
#define XT_UI_ARRANGEMENT_Y XT_UI_MARGIN_TOP
#define XT_UI_ARRANGEMENT_TABLE_OFFS_Y XT_UI_TITLEBAR_CONTENT_OFFS_Y

// Register Data Table.
#define XT_UI_REGDATA_X XT_UI_ARRANGEMENT_X
#define XT_UI_REGDATA_TABLE_OFFS_X 68
#define XT_UI_REGDATA_Y XT_UI_ARRANGEMENT_Y
#define XT_UI_REGDATA_TABLE_OFFS_Y (XT_UI_TITLEBAR_CONTENT_OFFS_Y)

// left side data
#define XT_UI_REGDATA_LEFTDAT_OFFS_X 0
#define XT_UI_REGDATA_LEFTDAT_NUM_OFFS_X (XT_UI_REGDATA_LEFTDAT_OFFS_X + 20)

#define XT_UI_REGDATA_TYPE_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y)
#define XT_UI_REGDATA_CON_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y + (1*8))
#define XT_UI_REGDATA_FL_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y + (2*8))
#define XT_UI_REGDATA_PMS_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y + (3*8))
#define XT_UI_REGDATA_AMS_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y + (4*8))

// con diagram
#define XT_UI_REGDATA_CONCHART_OFFS_X (XT_UI_REGDATA_LEFTDAT_OFFS_X + 28)
#define XT_UI_REGDATA_CONCHART_OFFS_Y (XT_UI_REGDATA_CON_OFFS_Y)

// op labels
#define XT_UI_REGDATA_OPLABELS_OFFS_X (XT_UI_REGDATA_LEFTDAT_OFFS_X + 58)
#define XT_UI_REGDATA_OPLABELS_OFFS_Y (XT_UI_REGDATA_TABLE_OFFS_Y)

// Spacing for number arrays (register data, ararnge, etc)
#define XT_UI_COL_SPACING 16
#define XT_UI_ROW_SPACING 8


#endif  // UI_METRICS_H
