#ifndef UI_METRICS_H
#define UI_METRICS_H

#define XT_UI_COL_SPACING 16
#define XT_UI_ROW_SPACING 8

#define XT_ARRANGE_RENDER_X 6
#define XT_ARRANGE_RENDER_Y 4

#define XT_INSTRUMENT_RENDER_X XT_ARRANGE_RENDER_X
#define XT_INSTRUMENT_RENDER_Y XT_ARRANGE_RENDER_Y


#endif  // UI_METRICS_H
